export const API_SUCCESS_CODES = {
  SUCCESS: 'SUCCESS',
  SERVER_HEALTH_OK: 'SERVER_HEALTH_OK',
  OTP_SENT: 'OTP_SENT',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
  USER_CREATED: 'USER_CREATED',
  USER_FETCHED: 'USER_FETCHED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  PROFILE_PICTURE_UPLOAD_URL_GENERATED: 'PROFILE_PICTURE_UPLOAD_URL_GENERATED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_RELISTED: 'PRODUCT_RELISTED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_IMAGE_DELETED: 'PRODUCT_IMAGE_DELETED',
  EXPIRED_INACTIVE_PRODUCTS_MARKED_AS_REMOVED: 'EXPIRED_INACTIVE_PRODUCTS_MARKED_AS_REMOVED',
  PRODUCT_OWNERSHIP_TRANSFERRED: 'PRODUCT_OWNERSHIP_TRANSFERRED',
  PRODUCT_OWNERSHIP_HISTORY_FETCHED: 'PRODUCT_OWNERSHIP_HISTORY_FETCHED',
  PRESIGNED_URLS_GENERATED: 'PRESIGNED_URLS_GENERATED',
  IMAGES_ADDED_TO_PRODUCT: 'IMAGES_ADDED_TO_PRODUCT',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  PUSH_DEVICE_REGISTERED: 'PUSH_DEVICE_REGISTERED',
  PUSH_DEVICE_UNREGISTERED: 'PUSH_DEVICE_UNREGISTERED',
  NOTIFICATION_MARKED_AS_READ: 'NOTIFICATION_MARKED_AS_READ',
  ALL_NOTIFICATIONS_MARKED_AS_READ: 'ALL_NOTIFICATIONS_MARKED_AS_READ',
  ALL_NOTIFICATIONS_CLEARED: 'ALL_NOTIFICATIONS_CLEARED',
  REQUEST_CREATED: 'REQUEST_CREATED',
  COUNTER_OFFER_CREATED: 'COUNTER_OFFER_CREATED',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  CONTACT_REVEAL_REQUESTED: 'CONTACT_REVEAL_REQUESTED',
  CONTACT_REVEAL_APPROVED: 'CONTACT_REVEAL_APPROVED',
  CONTACT_REVEAL_REJECTED: 'CONTACT_REVEAL_REJECTED',
  TRANSACTION_OTP_GENERATED: 'TRANSACTION_OTP_GENERATED',
  TRANSACTION_COMPLETED: 'TRANSACTION_COMPLETED',
} as const;

export const API_ERROR_CODES = {
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_CURSOR: 'INVALID_CURSOR',
  // Admin
  ADMIN_KEY_REQUIRED: 'ADMIN_KEY_REQUIRED',
  INVALID_ADMIN_KEY: 'INVALID_ADMIN_KEY',
  // Auth / OTP
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EMAIL_SEND_FAILED: 'OTP_EMAIL_SEND_FAILED',
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_FOUND_FOR_REFRESH_TOKEN: 'USER_NOT_FOUND_FOR_REFRESH_TOKEN',
  USER_EMAIL_OR_MOBILE_REQUIRED: 'USER_EMAIL_OR_MOBILE_REQUIRED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  MOBILE_ALREADY_IN_USE: 'MOBILE_ALREADY_IN_USE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  PARENT_CATEGORY_NOT_FOUND: 'PARENT_CATEGORY_NOT_FOUND',
  CATEGORY_SELF_PARENT: 'CATEGORY_SELF_PARENT',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_TRANSFER_NOT_OWNER: 'PRODUCT_TRANSFER_NOT_OWNER',
  PRODUCT_SAME_OWNER: 'PRODUCT_SAME_OWNER',
  PRODUCT_DELETE_NOT_OWNER: 'PRODUCT_DELETE_NOT_OWNER',
  PRODUCT_ALREADY_REMOVED: 'PRODUCT_ALREADY_REMOVED',
  PRODUCT_UPDATE_NOT_OWNER: 'PRODUCT_UPDATE_NOT_OWNER',
  PRODUCT_RELIST_NOT_OWNER: 'PRODUCT_RELIST_NOT_OWNER',
  PRODUCT_IN_COOLDOWN: 'PRODUCT_IN_COOLDOWN',
  PRODUCT_ALREADY_ACTIVE: 'PRODUCT_ALREADY_ACTIVE',
  PRODUCT_RELIST_INVALID_STATUS: 'PRODUCT_RELIST_INVALID_STATUS',
  PRODUCT_NOT_AVAILABLE_FOR_REQUESTS: 'PRODUCT_NOT_AVAILABLE_FOR_REQUESTS',
  PRODUCT_NOT_AVAILABLE_FOR_ACCEPTANCE: 'PRODUCT_NOT_AVAILABLE_FOR_ACCEPTANCE',
  PRODUCT_TEMPORARILY_DISABLED: 'PRODUCT_TEMPORARILY_DISABLED',
  PRODUCT_ONLY_ACCEPTS_PRODUCT_OFFERS: 'PRODUCT_ONLY_ACCEPTS_PRODUCT_OFFERS',
  PRODUCT_REUSED_IN_OFFER_LIST: 'PRODUCT_REUSED_IN_OFFER_LIST',
  OVERRIDE_LIMIT_EXCEEDED: 'OVERRIDE_LIMIT_EXCEEDED',
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  PRODUCT_IMAGE_DELETE_NOT_OWNER: 'PRODUCT_IMAGE_DELETE_NOT_OWNER',
  PRODUCT_UPLOAD_NOT_OWNER: 'PRODUCT_UPLOAD_NOT_OWNER',
  PRODUCT_ADD_IMAGES_NOT_OWNER: 'PRODUCT_ADD_IMAGES_NOT_OWNER',
  PRODUCT_FILE_COUNT_INVALID: 'PRODUCT_FILE_COUNT_INVALID',
  PRODUCT_IMAGE_COUNT_INVALID: 'PRODUCT_IMAGE_COUNT_INVALID',
  // Request / Offer
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_EXPIRED: 'REQUEST_EXPIRED',
  REQUEST_ALREADY_CLOSED: 'REQUEST_ALREADY_CLOSED',
  REQUEST_NOT_YOUR_TURN: 'REQUEST_NOT_YOUR_TURN',
  REQUEST_NOT_YOUR_TURN_ACCEPT: 'REQUEST_NOT_YOUR_TURN_ACCEPT',
  REQUEST_NOT_YOUR_TURN_REJECT: 'REQUEST_NOT_YOUR_TURN_REJECT',
  REQUEST_OWN_PRODUCT: 'REQUEST_OWN_PRODUCT',
  NO_ACTIVE_OFFER: 'NO_ACTIVE_OFFER',
  OFFER_REQUIRED: 'OFFER_REQUIRED',
  OFFER_PRODUCTS_REQUIRED: 'OFFER_PRODUCTS_REQUIRED',
  OFFER_AMOUNT_NOT_ALLOWED_FOR_PRODUCT: 'OFFER_AMOUNT_NOT_ALLOWED_FOR_PRODUCT',
  OFFER_AMOUNT_REQUIRED_FOR_MONEY: 'OFFER_AMOUNT_REQUIRED_FOR_MONEY',
  OFFER_PRODUCTS_NOT_ALLOWED_FOR_MONEY: 'OFFER_PRODUCTS_NOT_ALLOWED_FOR_MONEY',
  OFFER_PRODUCT_LISTS_NOT_ALLOWED_FOR_MONEY: 'OFFER_PRODUCT_LISTS_NOT_ALLOWED_FOR_MONEY',
  OFFER_MIXED_REQUIRES_AMOUNT_AND_PRODUCTS: 'OFFER_MIXED_REQUIRES_AMOUNT_AND_PRODUCTS',
  OFFER_MIXED_REQUIRES_AMOUNT: 'OFFER_MIXED_REQUIRES_AMOUNT',
  OFFER_MIXED_REQUIRES_AMOUNT_AND_REQUESTED_PRODUCTS:
    'OFFER_MIXED_REQUIRES_AMOUNT_AND_REQUESTED_PRODUCTS',
  OFFER_REQUESTED_PRODUCTS_REQUIRED: 'OFFER_REQUESTED_PRODUCTS_REQUIRED',
  COUNTER_OFFER_SELLER_OWN_LISTINGS: 'COUNTER_OFFER_SELLER_OWN_LISTINGS',
  // Reservation / Contact reveal
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  CONTACT_REVEAL_NOT_AVAILABLE: 'CONTACT_REVEAL_NOT_AVAILABLE',
  NO_ACTIVE_RESERVATION: 'NO_ACTIVE_RESERVATION',
  CONTACT_ALREADY_REVEALED: 'CONTACT_ALREADY_REVEALED',
  CONTACT_REVEAL_ALREADY_PENDING: 'CONTACT_REVEAL_ALREADY_PENDING',
  REVEAL_REQUEST_NOT_FOUND: 'REVEAL_REQUEST_NOT_FOUND',
  REVEAL_REQUEST_NOT_TARGET: 'REVEAL_REQUEST_NOT_TARGET',
  REVEAL_REQUEST_ALREADY_RESOLVED: 'REVEAL_REQUEST_ALREADY_RESOLVED',
  REVEAL_MISSING_PHONE: 'REVEAL_MISSING_PHONE',
  REVEAL_MISSING_EMAIL: 'REVEAL_MISSING_EMAIL',
  REVEAL_MISSING_CONTACT: 'REVEAL_MISSING_CONTACT',
  // Transaction
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_CANCELLED: 'TRANSACTION_CANCELLED',
  TRANSACTION_ALREADY_COMPLETED: 'TRANSACTION_ALREADY_COMPLETED',
  TRANSACTION_NOT_IN_PROGRESS: 'TRANSACTION_NOT_IN_PROGRESS',
  ACTIVE_TRANSACTION_NOT_FOUND: 'ACTIVE_TRANSACTION_NOT_FOUND',
  ONLY_BUYER_CAN_GENERATE_OTP: 'ONLY_BUYER_CAN_GENERATE_OTP',
  ONLY_SELLER_CAN_VERIFY_OTP: 'ONLY_SELLER_CAN_VERIFY_OTP',
  NO_ACTIVE_OTP: 'NO_ACTIVE_OTP',
  PRODUCTS_NO_LONGER_EXIST: 'PRODUCTS_NO_LONGER_EXIST',
  PRODUCTS_CHANGED_OWNERSHIP: 'PRODUCTS_CHANGED_OWNERSHIP',
  PRODUCTS_LOCKED_BY_RESERVATION: 'PRODUCTS_LOCKED_BY_RESERVATION',
  PRODUCTS_IN_ANOTHER_TRANSACTION: 'PRODUCTS_IN_ANOTHER_TRANSACTION',
} as const;

export type ApiSuccessCode = (typeof API_SUCCESS_CODES)[keyof typeof API_SUCCESS_CODES];
export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
export type ApiCode = ApiSuccessCode | ApiErrorCode;

export const API_MESSAGES: Record<ApiCode, string> = {
  [API_SUCCESS_CODES.SUCCESS]: 'Success',
  [API_SUCCESS_CODES.SERVER_HEALTH_OK]: 'Server is up and running',
  [API_SUCCESS_CODES.OTP_SENT]: 'OTP sent',
  [API_SUCCESS_CODES.LOGIN_SUCCESSFUL]: 'Login successful',
  [API_SUCCESS_CODES.TOKEN_REFRESHED]: 'Token refreshed successfully',
  [API_SUCCESS_CODES.LOGOUT_SUCCESSFUL]: 'Logout successful',
  [API_SUCCESS_CODES.USER_CREATED]: 'User created',
  [API_SUCCESS_CODES.USER_FETCHED]: 'User fetched',
  [API_SUCCESS_CODES.USER_PROFILE_UPDATED]: 'User profile updated',
  [API_SUCCESS_CODES.PROFILE_PICTURE_UPLOAD_URL_GENERATED]: 'Profile picture upload URL generated',
  [API_SUCCESS_CODES.PRODUCT_CREATED]: 'Product created',
  [API_SUCCESS_CODES.PRODUCT_DELETED]: 'Product deleted',
  [API_SUCCESS_CODES.PRODUCT_RELISTED]: 'Product relisted',
  [API_SUCCESS_CODES.PRODUCT_UPDATED]: 'Product updated',
  [API_SUCCESS_CODES.PRODUCT_IMAGE_DELETED]: 'Product image deleted',
  [API_SUCCESS_CODES.EXPIRED_INACTIVE_PRODUCTS_MARKED_AS_REMOVED]:
    'Expired inactive products marked as removed',
  [API_SUCCESS_CODES.PRODUCT_OWNERSHIP_TRANSFERRED]: 'Product ownership transferred',
  [API_SUCCESS_CODES.PRODUCT_OWNERSHIP_HISTORY_FETCHED]: 'Product ownership history',
  [API_SUCCESS_CODES.PRESIGNED_URLS_GENERATED]: 'Pre-signed URLs generated',
  [API_SUCCESS_CODES.IMAGES_ADDED_TO_PRODUCT]: 'Images added to product',
  [API_SUCCESS_CODES.CATEGORY_CREATED]: 'Category created',
  [API_SUCCESS_CODES.CATEGORY_UPDATED]: 'Category updated',
  [API_SUCCESS_CODES.CATEGORY_DELETED]: 'Category deleted',
  [API_SUCCESS_CODES.PUSH_DEVICE_REGISTERED]: 'Push device registered',
  [API_SUCCESS_CODES.PUSH_DEVICE_UNREGISTERED]: 'Push device unregistered',
  [API_SUCCESS_CODES.NOTIFICATION_MARKED_AS_READ]: 'Notification marked as read',
  [API_SUCCESS_CODES.ALL_NOTIFICATIONS_MARKED_AS_READ]: 'All notifications marked as read',
  [API_SUCCESS_CODES.ALL_NOTIFICATIONS_CLEARED]: 'All notifications cleared',
  [API_SUCCESS_CODES.REQUEST_CREATED]: 'Request created',
  [API_SUCCESS_CODES.COUNTER_OFFER_CREATED]: 'Counter offer created',
  [API_SUCCESS_CODES.REQUEST_ACCEPTED]: 'Request accepted',
  [API_SUCCESS_CODES.REQUEST_REJECTED]: 'Request rejected',
  [API_SUCCESS_CODES.REQUEST_CANCELLED]: 'Request cancelled',
  [API_SUCCESS_CODES.CONTACT_REVEAL_REQUESTED]: 'Contact reveal requested',
  [API_SUCCESS_CODES.CONTACT_REVEAL_APPROVED]: 'Contact reveal approved',
  [API_SUCCESS_CODES.CONTACT_REVEAL_REJECTED]: 'Contact reveal rejected',
  [API_SUCCESS_CODES.TRANSACTION_OTP_GENERATED]: 'OTP generated',
  [API_SUCCESS_CODES.TRANSACTION_COMPLETED]: 'Transaction completed',

  // General
  [API_ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [API_ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [API_ERROR_CODES.UNAUTHORIZED]: 'Unauthorized',
  [API_ERROR_CODES.FORBIDDEN]: 'Forbidden',
  [API_ERROR_CODES.INVALID_TOKEN]: 'Invalid token',
  [API_ERROR_CODES.NOT_FOUND]: 'Not Found',
  [API_ERROR_CODES.INVALID_CURSOR]: 'Invalid cursor',
  // Admin
  [API_ERROR_CODES.ADMIN_KEY_REQUIRED]: 'Admin key required',
  [API_ERROR_CODES.INVALID_ADMIN_KEY]: 'Invalid admin key',
  // Auth / OTP
  [API_ERROR_CODES.INVALID_REFRESH_TOKEN]: 'Invalid refresh token',
  [API_ERROR_CODES.OTP_EXPIRED]: 'OTP expired',
  [API_ERROR_CODES.INVALID_OTP]: 'Invalid OTP',
  [API_ERROR_CODES.OTP_EMAIL_SEND_FAILED]: 'Failed to send OTP email',
  // User
  [API_ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [API_ERROR_CODES.USER_NOT_FOUND_FOR_REFRESH_TOKEN]: 'User not found for refresh token',
  [API_ERROR_CODES.USER_EMAIL_OR_MOBILE_REQUIRED]: 'Email or Mobile is required',
  [API_ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [API_ERROR_CODES.EMAIL_ALREADY_IN_USE]: 'Email is already in use',
  [API_ERROR_CODES.MOBILE_ALREADY_IN_USE]: 'Mobile number is already in use',
  [API_ERROR_CODES.INVALID_FILE_TYPE]: 'Invalid file type. Only JPEG, PNG, WebP are allowed.',
  // Category
  [API_ERROR_CODES.CATEGORY_NOT_FOUND]: 'Category not found',
  [API_ERROR_CODES.CATEGORY_NAME_ALREADY_EXISTS]: 'Category with this name already exists',
  [API_ERROR_CODES.PARENT_CATEGORY_NOT_FOUND]: 'Parent category not found',
  [API_ERROR_CODES.CATEGORY_SELF_PARENT]: 'A category cannot be its own parent',
  [API_ERROR_CODES.CATEGORY_HAS_PRODUCTS]: 'Cannot delete category with associated products',
  [API_ERROR_CODES.CATEGORY_HAS_CHILDREN]: 'Cannot delete category with child categories',
  // Product
  [API_ERROR_CODES.PRODUCT_NOT_FOUND]: 'Product not found',
  [API_ERROR_CODES.PRODUCT_TRANSFER_NOT_OWNER]: 'You can only transfer your own product',
  [API_ERROR_CODES.PRODUCT_SAME_OWNER]: 'New owner must be different from current owner',
  [API_ERROR_CODES.PRODUCT_DELETE_NOT_OWNER]: 'You can only delete your own products',
  [API_ERROR_CODES.PRODUCT_ALREADY_REMOVED]: 'Product is already removed',
  [API_ERROR_CODES.PRODUCT_UPDATE_NOT_OWNER]: 'You can only update your own product',
  [API_ERROR_CODES.PRODUCT_RELIST_NOT_OWNER]: 'You can only relist your own product',
  [API_ERROR_CODES.PRODUCT_IN_COOLDOWN]: 'Product is still in cooldown',
  [API_ERROR_CODES.PRODUCT_ALREADY_ACTIVE]: 'Product is already active',
  [API_ERROR_CODES.PRODUCT_RELIST_INVALID_STATUS]:
    'Only inactive, exchanged or removed products can be relisted',
  [API_ERROR_CODES.PRODUCT_NOT_AVAILABLE_FOR_REQUESTS]: 'Product is not available for requests',
  [API_ERROR_CODES.PRODUCT_NOT_AVAILABLE_FOR_ACCEPTANCE]: 'Product is not available for acceptance',
  [API_ERROR_CODES.PRODUCT_TEMPORARILY_DISABLED]:
    'Product is temporarily disabled due to excessive overrides',
  [API_ERROR_CODES.PRODUCT_ONLY_ACCEPTS_PRODUCT_OFFERS]:
    'This product only accepts product-based offers',
  [API_ERROR_CODES.PRODUCT_REUSED_IN_OFFER_LIST]:
    'Requested product cannot be reused inside offer/visibility product lists',
  [API_ERROR_CODES.OVERRIDE_LIMIT_EXCEEDED]:
    'Override limit exceeded. Product has been blocked for 7 days',
  [API_ERROR_CODES.IMAGE_NOT_FOUND]: 'Image not found',
  [API_ERROR_CODES.PRODUCT_IMAGE_DELETE_NOT_OWNER]:
    'You can only delete images from your own products',
  [API_ERROR_CODES.PRODUCT_UPLOAD_NOT_OWNER]: 'You can only upload images to your own products',
  [API_ERROR_CODES.PRODUCT_ADD_IMAGES_NOT_OWNER]: 'You can only add images to your own products',
  [API_ERROR_CODES.PRODUCT_FILE_COUNT_INVALID]: 'You must provide 1-6 file names',
  [API_ERROR_CODES.PRODUCT_IMAGE_COUNT_INVALID]: 'You must provide 1-6 images',
  // Request / Offer
  [API_ERROR_CODES.REQUEST_NOT_FOUND]: 'Request not found',
  [API_ERROR_CODES.REQUEST_EXPIRED]: 'Request has expired',
  [API_ERROR_CODES.REQUEST_ALREADY_CLOSED]: 'Request is already closed',
  [API_ERROR_CODES.REQUEST_NOT_YOUR_TURN]: 'Not your turn to make a counter offer',
  [API_ERROR_CODES.REQUEST_NOT_YOUR_TURN_ACCEPT]: 'Not your turn to accept',
  [API_ERROR_CODES.REQUEST_NOT_YOUR_TURN_REJECT]: 'Not your turn to reject',
  [API_ERROR_CODES.REQUEST_OWN_PRODUCT]: 'You cannot request your own product',
  [API_ERROR_CODES.NO_ACTIVE_OFFER]: 'No active offer found to accept',
  [API_ERROR_CODES.OFFER_REQUIRED]: 'An offer is required for this product',
  [API_ERROR_CODES.OFFER_PRODUCTS_REQUIRED]: 'offeredProducts is required for PRODUCT offer type',
  [API_ERROR_CODES.OFFER_AMOUNT_NOT_ALLOWED_FOR_PRODUCT]:
    'amount is not allowed for PRODUCT offer type',
  [API_ERROR_CODES.OFFER_AMOUNT_REQUIRED_FOR_MONEY]: 'amount is required for MONEY offer type',
  [API_ERROR_CODES.OFFER_PRODUCTS_NOT_ALLOWED_FOR_MONEY]:
    'offeredProducts is not allowed for MONEY offer type',
  [API_ERROR_CODES.OFFER_PRODUCT_LISTS_NOT_ALLOWED_FOR_MONEY]:
    'Product lists are not allowed for MONEY offer type',
  [API_ERROR_CODES.OFFER_MIXED_REQUIRES_AMOUNT_AND_PRODUCTS]:
    'MIXED offer type requires both amount and offeredProducts',
  [API_ERROR_CODES.OFFER_MIXED_REQUIRES_AMOUNT]: 'MIXED offer type requires amount',
  [API_ERROR_CODES.OFFER_MIXED_REQUIRES_AMOUNT_AND_REQUESTED_PRODUCTS]:
    'MIXED offer type requires amount and requestedProducts',
  [API_ERROR_CODES.OFFER_REQUESTED_PRODUCTS_REQUIRED]:
    'requestedProducts is required for PRODUCT offer type',
  [API_ERROR_CODES.COUNTER_OFFER_SELLER_OWN_LISTINGS]:
    'Seller cannot include own listings in a counter offer',
  // Reservation / Contact reveal
  [API_ERROR_CODES.RESERVATION_NOT_FOUND]: 'Reservation not found',
  [API_ERROR_CODES.CONTACT_REVEAL_NOT_AVAILABLE]:
    'Contact reveal is only available for accepted reserved requests',
  [API_ERROR_CODES.NO_ACTIVE_RESERVATION]: 'No active reservation found for this request',
  [API_ERROR_CODES.CONTACT_ALREADY_REVEALED]: 'Contact info is already revealed',
  [API_ERROR_CODES.CONTACT_REVEAL_ALREADY_PENDING]: 'A contact reveal request is already pending',
  [API_ERROR_CODES.REVEAL_REQUEST_NOT_FOUND]: 'Reveal request not found',
  [API_ERROR_CODES.REVEAL_REQUEST_NOT_TARGET]:
    'Only the target user can respond to this reveal request',
  [API_ERROR_CODES.REVEAL_REQUEST_ALREADY_RESOLVED]: 'Reveal request is already resolved',
  [API_ERROR_CODES.REVEAL_MISSING_PHONE]:
    'Please add your phone number in profile before approving reveal',
  [API_ERROR_CODES.REVEAL_MISSING_EMAIL]:
    'Please add your email in profile before approving reveal',
  [API_ERROR_CODES.REVEAL_MISSING_CONTACT]:
    'Please add phone or email in profile before approving reveal',
  // Transaction
  [API_ERROR_CODES.TRANSACTION_NOT_FOUND]: 'Transaction not found',
  [API_ERROR_CODES.TRANSACTION_CANCELLED]: 'Transaction is cancelled',
  [API_ERROR_CODES.TRANSACTION_ALREADY_COMPLETED]: 'Transaction is already completed',
  [API_ERROR_CODES.TRANSACTION_NOT_IN_PROGRESS]:
    'Transaction must be in progress for OTP verification',
  [API_ERROR_CODES.ACTIVE_TRANSACTION_NOT_FOUND]: 'Active transaction not found',
  [API_ERROR_CODES.ONLY_BUYER_CAN_GENERATE_OTP]: 'Only buyer can generate OTP',
  [API_ERROR_CODES.ONLY_SELLER_CAN_VERIFY_OTP]: 'Only seller can verify OTP',
  [API_ERROR_CODES.NO_ACTIVE_OTP]: 'No active OTP found',
  [API_ERROR_CODES.PRODUCTS_NO_LONGER_EXIST]: 'One or more exchanged products no longer exist',
  [API_ERROR_CODES.PRODUCTS_CHANGED_OWNERSHIP]:
    'One or more exchanged products changed ownership before completion',
  [API_ERROR_CODES.PRODUCTS_LOCKED_BY_RESERVATION]:
    'One or more exchanged products are locked by another active reservation',
  [API_ERROR_CODES.PRODUCTS_IN_ANOTHER_TRANSACTION]:
    'One or more exchanged products are already in another transaction',
};

const MESSAGE_TO_CODE: Record<string, ApiCode> = Object.entries(API_MESSAGES).reduce(
  (acc, [code, message]) => {
    acc[message] = code as ApiCode;
    return acc;
  },
  {} as Record<string, ApiCode>,
);

export const isApiCode = (value: string): value is ApiCode => {
  return value in API_MESSAGES;
};

export const resolveApiMessage = (
  codeOrMessage: ApiCode | string,
): {
  code?: ApiCode;
  message: string;
} => {
  if (isApiCode(codeOrMessage)) {
    return { code: codeOrMessage, message: API_MESSAGES[codeOrMessage] };
  }

  const matchedCode = MESSAGE_TO_CODE[codeOrMessage];
  if (matchedCode) {
    return { code: matchedCode, message: API_MESSAGES[matchedCode] };
  }

  return { message: codeOrMessage };
};
